package com.AppEnums;

/**
 * Created by Naresh on 26-Dec-16.
 */

public enum UIEventType {

    SEARCH_PROPERTY,
    DEFAULT_CALLS,
    GET_VERSION,
    RETRY_GET_LOCATIONS,
    RETRY_ALERT, RETRY_CITY_FEDED,
    RETRY_GET_CITY,
    RETRY_FEATURE_PROJECTS,
    RETRY_HOT_PROJECTS,
    RETRY_FEV, RETRY_SEARCH_PROJECTS, RETRY_APPLY_FILTER, RETRY_PROJECT_DETAILS, RETRY_POST_COMMENT, RETRY_HOME_PAGE, RETRY_LOGIN, RETRY_PRIVACY, RETRY_TNC, RETRY_FB_LOGIN, RETRY_GPLUS_LOGIN, RETRY_FORGOT_PWD, RETRY_REGISTER, SITE_VISIT_TIME, RETRY_SITEVISIT, GET_PERSONAL_DETAILS, RETRY_MAKE_PAYMENT, SITE_VISIT_TIME_2, RETRY_UNIT_DETAILS, RETRY_PDF_DOWNLOAD, RETRY_GALLERY, RETRY_ENQUIRY, RETRY_LOTTERY_PROJECT, RETRY_UNIT_MAP, RETRY_PAYMENT_PLAN, RETRY_LOAD_URL, RETRY_DATA_URL, RETRY_TRANSACTION_STATUS;
}
